// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfgmvudpmrfwizkdyxlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZ212dWRwbXJmd2l6a2R5eGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDI4MTksImV4cCI6MjA2MTg3ODgxOX0.BHhUQbMt_ZkAp-wuQNmQ9DRK6QuFISUDka7ujVeRASA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);